### ISSUE TITLE
当前bug及解决方案

### ISSUE THREAD

**Issue by yuhaizr** [moell-peng/moell-blog#11]
1、标签跳转有bug
blog详情页面，根据标签进行跳转的时候回报错，只需要在app/Http/Controllers/TagController.php 中添加
use App\Models\Tag;

2、多说评论short_name 不存在时错误 
  需要添加字段是否存在的判断就好了。resources/views/backend/system/index.blade.php
`                                <div class='col-md-6'>
                                    <input type="text"  value="{{ $system['duoshuo_short_name'])? $system['duoshuo_short_name'] : '' }}"
                                           class='form-control'
                                           name="duoshuo_short_name"
                                           id="duoshuo_short_name"
                                           placeholder="请输入多说评论short_name">
                                </div>`

修改为
`
                                <div class='col-md-6'>
                                    <input type="text"  value="{{ isset($system['duoshuo_short_name']) ? $system['duoshuo_short_name'] : '' }}"
                                           class='form-control'
                                           name="duoshuo_short_name"
                                           id="duoshuo_short_name"
                                           placeholder="请输入多说评论short_name">
                                </div>
`

最后感谢作者的分享，接下来我也会在此基础上不断扩展新功能。附上自己的blog
https://blog.yuhai.xin/

**Comment by moell-peng** [comment]
@yuhaizr ,1已修复，2 后续会将多说（官方已关闭了）移除
