### ISSUE TITLE
执行数据库迁移报错  Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1071 Specif ied key was too long; max key length is 1000 bytes")

### ISSUE THREAD

**Issue by liuxiaojin93** [moell-peng/moell-blog#12]
执行 php artisan migrate,解决设置 
在app/Providers/AppServiceProvider.php中修改
use Illuminate\Support\Facades\Schema;
public function boot()
    {
        //
      Schema::defaultStringLength(191);
    }
然后再执行 php artisan migrate

**Comment by moell-peng** [comment]
@liuxiaojin93 建议升级mysql版本至>=5.7 吧，Laravel 现在也是这样要求的。
