### ISSUE TITLE
评论插件加载不出来是怎么回事

### ISSUE THREAD

**Issue by hejindan** [moell-peng/moell-blog#3]
评论插件加载不出来是怎么回事

**Comment by moell-peng** [comment]
首先在设置中确保选择了评论插件和正确的评论插件short_name， 如果是 disqus 的话是被墙了的。你可以右键源代码看看.

**Comment by hejindan** [comment]
正确的short_name 是啥？

**Comment by moell-peng** [comment]
评论使用的是第三方评论插件多说和 disqus 你去申请short_name 吧
