### ISSUE TITLE
跑不起来

### ISSUE THREAD

**Issue by yaowen2011** [moell-peng/moell-blog#4]
Whoops, looks like something went wrong.
1/1 FatalErrorException in AliasLoader.php line 63: Maximum function nesting level of '100' reached, aborting!

    in C:\xampp\htdocs\moell-blog-master\vendor\laravel\framework\src\Illuminate\Foundation\AliasLoader.php line 63

**Comment by moell-peng** [comment]
你使用了xdebug,xdebug默认设置了函数最大嵌套数为100.你修改一下你的php.ini,将xdebug.max_nesting_level 设置为500 或者更大，然后重启你的apache

**Comment by yaowen2011** [comment]
我修改了  xdebug.max_nesting_level=600  这个就可以了    原来一次loadClass的调用真的超过100了
